// ┌──────────────────────────────────────────────────────────────────────┐
// │  export.go — Pin Configuration Export                               │
// └──────────────────────────────────────────────────────────────────────┘
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/amken3d/Pingo/pindata"
	"github.com/ncruces/zenity"
)

// lastExportDir remembers the last directory the user exported to.
var lastExportDir = defaultExportDir()

func defaultExportDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return home
}

// saveExport opens a native save-file dialog with the given default filename
// and file type filter, then writes the content to the chosen path.
func saveExport(defaultName, filterName, filterPattern, content string) {
	go func() {
		path, err := zenity.SelectFileSave(
			zenity.Title("Export Pin Configuration"),
			zenity.Filename(filepath.Join(lastExportDir, defaultName)),
			zenity.FileFilter{Name: filterName, Patterns: []string{filterPattern}},
			zenity.ConfirmOverwrite(),
		)
		if err != nil || path == "" {
			return
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			exportStatus.Set("Error: " + err.Error())
			return
		}
		lastExportDir = filepath.Dir(path)
		exportStatus.Set(fmt.Sprintf("Exported to %s", path))
	}()
}

// ─── Export Formatters ───────────────────────────────────────────────

func exportCHeader(sel map[int]pindata.Function, names map[int]string) string {
	var b strings.Builder
	spec := currentSpec()
	b.WriteString("// Pin configuration generated by Pingo\n")
	b.WriteString(fmt.Sprintf("// Board: %s\n\n", spec.Name))
	b.WriteString("#ifndef PINGO_PINS_H\n#define PINGO_PINS_H\n\n")
	for _, gp := range sortedGPIOs(sel) {
		fn := sel[gp]
		name := names[gp]
		if name == "" {
			name = sanitizeIdentifier(fn.Name)
		} else {
			name = sanitizeIdentifier(name)
		}
		b.WriteString(fmt.Sprintf("#define PIN_%-20s %d  // GP%d - %s (%s)\n",
			strings.ToUpper(name), gp, gp, fn.Name, fn.Category))
	}
	b.WriteString("\n#endif // PINGO_PINS_H\n")
	return b.String()
}

func exportTinyGo(sel map[int]pindata.Function, names map[int]string) string {
	var b strings.Builder
	spec := currentSpec()
	b.WriteString("// Pin configuration generated by Pingo\n")
	b.WriteString(fmt.Sprintf("// Board: %s\n\n", spec.Name))
	b.WriteString("package main\n\nimport \"machine\"\n\nvar (\n")
	for _, gp := range sortedGPIOs(sel) {
		fn := sel[gp]
		name := names[gp]
		if name == "" {
			name = sanitizeIdentifier(fn.Name)
		} else {
			name = sanitizeIdentifier(name)
		}
		b.WriteString(fmt.Sprintf("\t%s = machine.GP%d // %s (%s)\n",
			name, gp, fn.Name, fn.Category))
	}
	b.WriteString(")\n")
	return b.String()
}

func exportMicroPython(sel map[int]pindata.Function, names map[int]string) string {
	var b strings.Builder
	spec := currentSpec()
	b.WriteString("# Pin configuration generated by Pingo\n")
	b.WriteString(fmt.Sprintf("# Board: %s\n\n", spec.Name))
	b.WriteString("from machine import Pin\n\n")
	for _, gp := range sortedGPIOs(sel) {
		fn := sel[gp]
		name := names[gp]
		if name == "" {
			name = sanitizeIdentifier(fn.Name)
		} else {
			name = sanitizeIdentifier(name)
		}
		b.WriteString(fmt.Sprintf("%-20s = %d  # GP%d - %s (%s)\n",
			strings.ToUpper(name), gp, gp, fn.Name, fn.Category))
	}
	return b.String()
}

func exportCSV(sel map[int]pindata.Function, names map[int]string) string {
	var b strings.Builder
	b.WriteString("GPIO,Function,Category,Custom Name\n")
	for _, gp := range sortedGPIOs(sel) {
		fn := sel[gp]
		name := names[gp]
		b.WriteString(fmt.Sprintf("GP%d,%s,%s,%s\n", gp, fn.Name, fn.Category, name))
	}
	return b.String()
}

// sanitizeIdentifier converts a string to a valid C/Go identifier.
func sanitizeIdentifier(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			b.WriteRune(c)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}
